final_model_name: ""
pre-train_method: "dino"
backbone:
  name: "resnet50"
max_epochs: 400
devices: [0]

merge_config_file: ""
data:
	dataset_name: ""
	annotations_file: ""
	train_path: ""
	test_path: ""
	num_classes:
	num_workers: 4
model:
	pretrained_weights: ""
	device: "cuda"  # "cpu"
	score_thresh_test: 0.5
solver:
	img_per_batch: 2
	base_lr: 0.000125
	max_iters: 18000
	steps: (12000, 16000)
	gamma: 0.1
	warmup_iters: 1000
output_dir: "../output"




