params:
 final_model_name: dinotron_merged_price_labels
 pretrain_method: dino
 backbone: resnet50
 trainer: custom # default, custom
 max_epochs: 400
 resume: True
 device: cuda  # cpu
 devices: [0]

paths:
 merge_config_file: ${hydra:runtime.cwd}/merge_configs/faster_rcnn_R_50_C4_1x.yaml
 pretrained_weights: /home/karun95/notebooks/merged_pricetag_dinotron_model.pkl # detectron2://ImageNetPretrained/MSRA/R-50.pkl
 train_image_path: /home/karun95/master_thesis/datasets/esl_price_tags_dataset/esl_detection/train_dir/train_img_dir
 train_annotations_file: /home/karun95/master_thesis/datasets/esl_price_tags_dataset/esl_detection/train_dir/_modified_annotations.coco.json
 test_image_path: /home/karun95/master_thesis/datasets/esl_price_tags_dataset/esl_detection/test_dir/test_img_dir
 test_annotations_file: /home/karun95/master_thesis/datasets/esl_price_tags_dataset/esl_detection/test_dir/_modified_annotations.coco.json
 validation_image_path: /home/karun95/master_thesis/datasets/esl_price_tags_dataset/esl_detection/val_dir/val_img_dir
 validation_annotations_file: /home/karun95/master_thesis/datasets/esl_price_tags_dataset/esl_detection/val_dir/_modified_annotations.coco.json
 output_dir: dinotron_mpl_experiments
 config_save_name: dinotron_price_labels
 pickle_config_file_path: /home/karun95/dinotron/dinotron/downstream/object_detection/detectron_output/dinotron_mpl_experiments/dinotron_merged_price_labels_config.pkl

data:
 dataset_name: esl_detection_100perc
 label_fraction: 100 # in percent
 num_classes: 1
 num_workers: 4
 classes: ["price_label"]
 register_dataset: auto # manual

model:
 score_thresh_test: 0.5
 batch_size_per_image: 512
 backbone_freeze_at: 4
 test_eval: 200

solver:
 img_per_batch: 2
 base_lr: 0.00025
 max_iters: 400
 steps: [12000, 16000]
 gamma: 0.1
 warmup_iters: 1000

mlflow:
 tracking_uri: "http://localhost:5000"
 experiment_name: price_labels
 run_name: price_test
 run_description: price_labels fine tuning