params:
 final_model_name:
 pretrain_method: dino # imagenet, dino
 backbone: resnet50
 trainer: custom # default, custom
 max_epochs:
 resume: True
 device: cuda  # cpu
 devices: [0]

paths:
 merge_config_file:
 pretrained_weights:
 train_image_path:
 train_annotations_file:
 test_image_path:
 test_annotations_file:
 validation_image_path:
 validation_annotations_file:
 output_dir:
 config_save_name:
 pickle_config_file_path:

data:
 dataset_name:
 label_fraction:
 num_classes:
 num_workers:
 classes:
 register_dataset: auto # manual

model:
 score_thresh_test: 0.5
 batch_size_per_image: 512
 backbone_freeze_at: 4
 test_eval: 5000

solver:
 img_per_batch: 2
 base_lr: 0.00025
 max_iters: 18000
 steps: [12000, 16000]
 gamma: 0.1
 warmup_iters: 1000

mlflow:
 tracking_uri:
 experiment_name:
 run_name:
 run_description:

evaluate:
 test_dataset_name:
 test_images :
 test_annotations :
 config_file_path :
 model_output_dir :
 model_name : "model_final.pth"