params:
 final_model_name: dino_rpl
 pretrain_method: dino
 backbone: resnet50
 trainer: default # custom,student,teacher
 max_epochs: 400
 resume: False
 device: cuda  # cpu
 devices: [0]

paths:
 merge_config_file: ${hydra:runtime.cwd}/merge_configs/faster_rcnn_R_50_C4_3x.yaml
 pretrained_weights: detectron2://ImageNetPretrained/MSRA/R-50.pkl
 annotations_file: _annotations.coco.json
 train_data_path: /home/karun95/master_thesis/datasets/russian_price_labels_dataset/russian_price_labels/price_labels_train/
 test_data_path: /home/karun95/master_thesis/datasets/russian_price_labels_dataset/russian_price_labels/price_labels_test/
 output_dir: ./detectron_output

data:
 dataset_name: russian_price_labels
 label_fraction: 100 # in percent
 num_classes: 5
 num_workers: 4
 classes: ["text", "name", "old_price", "price", "promotion"]

model:
 score_thresh_test: 0.5
 batch_size_per_image: 512

solver:
 img_per_batch: 2
 base_lr: 0.000125
 max_iters: 18000
 steps: [12000, 16000]
 gamma: 0.1
 warmup_iters: 1000


